# Array creation routines 数组创建

## Ones and zeros

In [1]:
import numpy as np

函数|描述
---|---
array	|转换输入数据（列表，数组或其它序列类型）到一个ndarray，可以推断一个dtype或明确的设置一个dtype。默认拷贝输入数据。
asarray	|转换输入为一个ndarray，当输入已经是一个ndarray时就不拷贝。
arange	|同内建的range函数，但不返回列表而是一个ndarray
ones, ones_like	|根据提供的shape和dtype产生一个全1的数组。ones_like使用另一歌数组为入参，产生一个shape和dtype都相同的数组。
zeros, zeros_like	|同ones和ones_like，但是生成全0的数组
empty, enpty_like	|通过分配新内存来构造新的数组，但不同与ones 和 zeros，不初始任何值。
eye, identity	|生成一个NxN的单位方阵（对角线上为1，其它地方为0）

Create a new array of 2*2 integers, without initializing entries.

In [6]:
# np.empty()不对内容进行初始化，只分配内存空间。内容常常是未初始化的垃圾值.
np.empty([2,2], int)  

array([[1208,    0],
       [1208,    0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [20]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
X

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 用来创建和另一个数组相同的数组
np.empty_like(X)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [9]:
# 创建对角线数组(参数) 参数表示维度
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [10]:
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

Create a new array of 3*2 float numbers, filled with ones.and filled with zeros.

In [15]:
np.ones([3,2],float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [16]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [25]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3], dtype=int64)

In [24]:
# np.ones_like() 创建和上行数组x相同的数组，用1填充
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [28]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3], dtype=int64)

In [29]:
# zeros_like() 创建和上行数组x相同的数组，用0填充
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [31]:
# 方法一：创建数组,用指定的数字去填充。
np.full((2,5),6,int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [34]:
# 方法二：通过数组计算，将单位数组乘倍数得到
np.ones((2,5),int) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [38]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3], dtype=int64)

In [36]:
# 创建一个和x相同的数组，用6去填充
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

In [39]:
np.ones_like(x) * 6

array([6, 6, 6, 6], dtype=int64)

## From existing data 从现有数据创建

Create an array of [1, 2, 3].

In [40]:
np.array((1,2,3))

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [45]:
# 将列表转换为numpy数组
x = [1,2]
np.asarray(x)

[1, 2]

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [52]:
X = np.array([[1, 2], [3, 4]])
# 创建与数组结构相同的矩阵matrix
Y = np.asmatrix(X)
Y

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [54]:
x = [1, 2]
# 第一种
np.asarray(x,float)
# 第二种
np.asfarray(x)

array([ 1.,  2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.(将其转换为其单个元素的标量scalar，即30。)

In [56]:
x = np.array([30])
# 将单元素数组转换为标量 
np.asscalar(x)

array([30])

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [58]:
x = np.array([1, 2, 3])
# 复制数组
y = np.copy(x)
print(id(x),x)
print(id(y),y)

2894683218048 [1 2 3]
2894683196512 [1 2 3]


## Numerical ranges 指定范围内创建数组 （随机）

Create an array of step.

In [61]:
x = np.arange(1,21)
# 也可以加入步长
y = np.arange(1,21,2)
print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


Create a 1-D array of 10 evenly spaced elements between 3. and 10., inclusive.

* numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

    1. num : int, optional(可选)
     生成的样本数，默认是50。必须是非负。

    2. endpoint : bool, optional
     如果是真，则一定包括stop，如果为False，一定不会有stop

    3. retstep : bool, optional
     If True, return (samples, step), where step is the spacing between sample

In [74]:
# 对于浮点类型的数组，给出范围和步长，通常很难预测元素的数量（与浮点数的精度有关），因此对于浮点类型数组，最好指定其元素个数，而不是其步长。

x = np.linspace(2.0, 3.0, num=5)
y = np.linspace(0., 10.0, 10)
print(x)
print(y)

[ 2.    2.25  2.5   2.75  3.  ]
[  0.           1.11111111   2.22222222   3.33333333   4.44444444
   5.55555556   6.66666667   7.77777778   8.88888889  10.        ]


Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [86]:
# logspace中，开始点和结束点是10的幂，0代表10的0次方，9代表10的9次方。参数：5 表示的是几个元素  base默认为10.
np.logspace(0, 9, 10,base=10)

array([  1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03,   1.00000000e+04,   1.00000000e+05,
         1.00000000e+06,   1.00000000e+07,   1.00000000e+08,
         1.00000000e+09])

In [89]:
# 假如，我们想要改变基数，不让它以10为底数，我们可以改变base参数
# 创建了4个元素的数组，范围在 2的0次方 到 2的5次方
np.logspace(0,5,4,base=2)

array([  1.       ,   3.1748021,  10.0793684,  32.       ])

## Building matrices 构建矩阵

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].
 * 设x数组（[〔0, 1, 2，3〕，〔4, 5, 6〕，7〕，〔8, 9, 10〕〕〕得到x的对角线，即，[0, 5, 10 ]。

In [90]:
X = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7], 
              [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [94]:
X = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9, 10, 11]]).diagonal()
X

array([ 0,  5, 10])

In [95]:
X = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.
* 创建一个二维数组，其对角线等于[1，2，3，4]其他元素为0.

In [95]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])
* 创建一个下三角数组

In [102]:
# tri() 第三个参数是关键，如下三个数组，注意观察区别
np.tri(3, 5, -0)   

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.]])

In [100]:
np.tri(3, 5, -1)  

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [101]:
np.tri(3, 5, -2)  

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [103]:
# tril(指定范围.定义现状，参数决定下三角的层次)
np.tril(np.arange(1, 13).reshape(4, 3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [107]:
# triu(指定范围.定义现状，参数决定上三角的层次)
np.triu(np.arange(1,13).reshape(4,3), -0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [108]:
np.triu(np.arange(1,13).reshape(4,3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [109]:
np.triu(np.arange(1,13).reshape(4,3), -2)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12]])